freebsd_instance:
  image: freebsd-13-0-release-amd64

task:
  install_script: pkg install -y cmake ninja
  script: |
      mkdir Build
      cd Build
      cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
      ninja
      ctest -j4
