resources:
- repo: self

phases:
- phase: Linux
  queue:
    name: 'Hosted Ubuntu 2004'
    parallel: 2
    matrix:
      Debug:
        BuildType: Debug
      Release:
        BuildType: Release

  steps:
  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo apt-get update
      sudo apt-get install -y ninja-build
      sudo apt-get install gcc-10 g++-10


  - task: CMake@1
    inputs:
      cmakeArgs: '.. -GNinja -DCMAKE_BUILD_TYPE=$(BuildType) -DENABLE_TESTS=ON -DCMAKE_CXX_COMPILER=g++-10'

  - script: |
      ninja

    workingDirectory: build
    failOnStderr: true
    displayName: 'Compile'

  - script: |
      ctest -j 4 --output-on-failure

    workingDirectory: build
    failOnStderr: true
    displayName: 'Test'

- phase: macOS
  queue:
    name: 'Hosted macOS'
    parallel: 2
    matrix:
      Debug:
        BuildType: Debug
      Release:
        BuildType: Release

  steps:
  - task: CMake@1
    displayName: 'CMake .. -DCMAKE_BUILD_TYPE=$(BuildType)'
    inputs:
      cmakeArgs: '.. -DCMAKE_BUILD_TYPE=$(BuildType) -DENABLE_TESTS=ON'

  - script: |
      make -j 4

    workingDirectory: build
    failOnStderr: true
    displayName: 'Compile'

  - script: |
      ctest -j 4 --output-on-failure

    workingDirectory: build
    failOnStderr: true
    displayName: 'Test'

