name: DTC CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        config:
        - {
            name: "Ubuntu Release",
            os: "ubuntu-latest",
            build-type: Release,
            dependencies: "sudo apt install ninja-build"
          }
        - {
            name: "macOS Release",
            os: "macos-latest",
            build-type: Release,
            dependencies: "rm -f /usr/local/bin/2to3 ; brew update && brew install cmake ninja"
          }
        - {
            name: "Ubuntu Debug",
            os: "ubuntu-latest",
            build-type: Debug,
            dependencies: "sudo apt install ninja-build"
          }
        - {
            name: "macOS Debug",
            os: "macos-latest",
            build-type: Debug,
            dependencies: "rm -f /usr/local/bin/2to3 ; brew update && brew install cmake ninja"
          }
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}
    steps:
    - uses: actions/checkout@v4
    - name: Install ninja
      run: ${{ matrix.config.dependencies }}
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build-type}} -G Ninja
    - name: Build
      working-directory: ${{github.workspace}}/build
      # Build your program with the given configuration
      run: NINJA_STATUS="%p [%f:%s/%t] %o/s, %es " ninja
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Build your program with the given configuration
      run: ctest --output-on-failure -j 4
